name: gerenciador-metas-server

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5433:5432'  # Mapeia a porta 5432 do host para a porta 5432 do container
    environment:
      - POSTGRES_USER=docker        # Nome do usuário do PostgreSQL
      - POSTGRES_PASSWORD=postgres     # Senha do usuário do PostgreSQL
      - POSTGRES_DB=inorbt           # Nome do banco de dados a ser criado

